on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python quality and format checker
        uses: konstruktoid/action-pylint@v0.0.8

